"""
XSIAM Content Pack Generator
Exports converted rules to XSIAM-compatible content pack format
"""
import json
import os
import zipfile
from io import BytesIO
from typing import List, Dict
from datetime import datetime

def generate_pack_metadata(pack_name: str, description: str, author: str = "Migration Assistant") -> Dict:
    """Generate pack_metadata.json content"""
    return {
        "name": pack_name,
        "description": description,
        "support": "community",
        "currentVersion": "1.0.0",
        "author": author,
        "url": "",
        "email": "",
        "created": datetime.now().isoformat(),
        "categories": ["Analytics & SIEM"],
        "tags": ["migration", "detection", "correlation"],
        "useCases": ["SIEM Migration"],
        "keywords": ["splunk", "qradar", "migration"]
    }

def generate_correlation_rule(rule: Dict, index: int) -> Dict:
    """
    Generate a correlation rule JSON for XSIAM
    Based on XSIAM correlation rule structure
    """
    return {
        "rule_id": f"migration_rule_{index:03d}",
        "rule_name": rule.get("name", f"Migrated Rule {index}"),
        "description": rule.get("description", "Migrated detection rule"),
        "severity": "medium",
        "status": "enabled",
        "xql_query": rule.get("converted_query", ""),
        "metadata": {
            "source_platform": rule.get("source_platform", "unknown"),
            "original_query": rule.get("original_query", ""),
            "migration_timestamp": datetime.now().isoformat(),
            "migration_status": rule.get("status", "pending")
        },
        "alert_fields": [
            "actor_effective_username",
            "action_local_ip",
            "action_remote_ip",
            "causality_actor_process_image_name"
        ],
        "dedup_period": 3600,
        "aggregation_window": 300
    }

def generate_readme(rules_count: int, source_platforms: List[str]) -> str:
    """Generate README.md for the content pack"""
    platforms_str = ", ".join(set(source_platforms))
    return f"""# Migrated Detection Rules Content Pack

This content pack contains {rules_count} migrated detection rules from {platforms_str}.

## Contents

- **Correlation Rules**: {rules_count} rules converted to XQL format
- **Source Platforms**: {platforms_str}
- **Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Installation

1. Upload this content pack to your XSIAM tenant
2. Navigate to Settings → Content Management → Upload Content Pack
3. Select this ZIP file
4. Review and enable the correlation rules as needed

## Notes

- All rules have been automatically converted from their source format to XQL
- Review each rule's XQL query before enabling in production
- Adjust severity levels and alert fields as needed for your environment
- Original queries are preserved in the metadata for reference

## Support

This content pack was generated by the XSIAM Migration Assistant tool.
"""

def create_content_pack(rules: List[Dict], pack_name: str = "MigratedRules") -> BytesIO:
    """
    Create a complete XSIAM content pack ZIP file
    
    Args:
        rules: List of rule dictionaries with name, converted_query, etc.
        pack_name: Name of the content pack
        
    Returns:
        BytesIO object containing the ZIP file
    """
    zip_buffer = BytesIO()
    
    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
        # Create pack metadata
        pack_meta = generate_pack_metadata(
            pack_name=pack_name,
            description=f"Content pack with {len(rules)} migrated detection rules"
        )
        zip_file.writestr(f"{pack_name}/pack_metadata.json", json.dumps(pack_meta, indent=2))
        
        # Create CorrelationRules directory with individual rule files
        source_platforms = []
        for idx, rule in enumerate(rules, start=1):
            if rule.get("source_platform"):
                source_platforms.append(rule["source_platform"])
            
            correlation_rule = generate_correlation_rule(rule, idx)
            rule_filename = f"{pack_name}/CorrelationRules/rule_{idx:03d}_{rule.get('name', 'unnamed').replace(' ', '_')[:30]}.json"
            zip_file.writestr(rule_filename, json.dumps(correlation_rule, indent=2))
        
        # Create README
        readme_content = generate_readme(len(rules), source_platforms)
        zip_file.writestr(f"{pack_name}/README.md", readme_content)
    
    zip_buffer.seek(0)
    return zip_buffer
